# Generated by Django 2.2.13 on 2020-06-22 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200622_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=149, unique=True)),
                ('horizontal_banner', models.FileField(blank=True, null=True, upload_to='pictures/')),
                ('horizontal_banner_title', models.CharField(max_length=149, unique=True)),
                ('horizontal_banner_link', models.URLField(default='https://google.com')),
                ('vertical_banner', models.FileField(blank=True, null=True, upload_to='pictures/')),
                ('vertical_banner_title', models.CharField(max_length=149, unique=True)),
                ('vertical_banner_link', models.URLField(default='https://google.com')),
                ('link_1', models.URLField(default='https://google.com')),
                ('link_title_1', models.CharField(max_length=149, unique=True)),
                ('link_2', models.URLField(default='https://google.com')),
                ('link_title_2', models.CharField(max_length=149, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_event', to='events.Event')),
            ],
        ),
    ]
