# Generated by Django 2.2.13 on 2020-06-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='horizontal_banner_link',
            field=models.URLField(blank=True, default='https://google.com', null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='horizontal_banner_title',
            field=models.CharField(blank=True, max_length=149, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='link_2',
            field=models.URLField(blank=True, default='https://google.com', null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='link_title_1',
            field=models.CharField(blank=True, max_length=149, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='link_title_2',
            field=models.CharField(blank=True, max_length=149, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='vertical_banner_link',
            field=models.URLField(blank=True, default='https://google.com', null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='vertical_banner_title',
            field=models.CharField(blank=True, max_length=149, null=True, unique=True),
        ),
    ]
