# Generated by Django 2.2.13 on 2020-06-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20200622_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='horizontal_banner_title',
            field=models.CharField(blank=True, max_length=149, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='link_title_1',
            field=models.CharField(blank=True, max_length=149, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='link_title_2',
            field=models.CharField(blank=True, max_length=149, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='vertical_banner_title',
            field=models.CharField(blank=True, max_length=149, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=149, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='icon',
            field=models.CharField(blank=True, max_length=149, null=True),
        ),
    ]
