# Generated by Django 2.2.13 on 2020-06-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20200622_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='language',
            field=models.CharField(blank=True, max_length=149, null=True),
        ),
    ]
