# Generated by Django 2.2.13 on 2020-06-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20200624_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='chat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='live_video',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='own_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='own_liveplayer',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Landing',
        ),
    ]
