# Generated by Django 2.2.13 on 2020-07-30 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_liveplayer_type_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=149, unique=True)),
                ('date', models.CharField(max_length=149, unique=True)),
                ('time', models.TextField(max_length=249)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_element_room', to='events.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=149, unique=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_event', to='events.Event')),
            ],
        ),
    ]
