# Generated by Django 2.2.13 on 2020-07-30 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20200730_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmeelement',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programme_element_programme', to='events.Programme'),
        ),
        migrations.AlterField(
            model_name='programmeelement',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programme_element_room', to='events.Room'),
        ),
    ]
