# Generated by Django 2.2.13 on 2020-07-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_auto_20200730_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmeelement',
            name='date',
            field=models.CharField(max_length=149),
        ),
        migrations.AlterField(
            model_name='programmeelement',
            name='title',
            field=models.CharField(max_length=149),
        ),
    ]
