# Generated by Django 2.2.13 on 2020-10-22 18:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_auto_20200730_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiritualSupportRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=149, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='spiritualsupport/')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=149)),
                ('description', models.TextField(blank=True, null=True)),
                ('banner_1', models.FileField(blank=True, null=True, upload_to='banners/')),
                ('use_banner_1', models.BooleanField(default=False)),
                ('banner_2', models.FileField(blank=True, null=True, upload_to='banners/')),
                ('use_banner_2', models.BooleanField(default=False)),
                ('link_1', models.URLField(blank=True, default='', null=True)),
                ('link_1_text', models.CharField(blank=True, max_length=300, null=True)),
                ('use_link_1', models.BooleanField(default=False)),
                ('link_2', models.URLField(blank=True, default='', null=True)),
                ('link_2_text', models.CharField(blank=True, max_length=300, null=True)),
                ('use_link_2', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teamedition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=149)),
                ('content', ckeditor.fields.RichTextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='UserGuideArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(default='')),
            ],
        ),
    ]
