# Generated by Django 2.2.13 on 2020-10-22 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_spiritualsupportrequest_sponsors_teamedition_userguidearticle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sponsors',
            new_name='Sponsor',
        ),
    ]
