# Generated by Django 2.2.13 on 2020-10-22 21:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_auto_20201022_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spiritualsupportrequest',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
