# Generated by Django 2.2.13 on 2020-10-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_auto_20201022_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamedition',
            name='image',
            field=models.FileField(blank=True, help_text='sube tu pago aqui (pdf o imagen)', null=True, upload_to='te/'),
        ),
    ]
