# Generated by Django 2.2.13 on 2020-10-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_teamedition_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamedition',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='te/'),
        ),
    ]
