version: '3.7'

services:
  web:
    build: ./
    command: gunicorn OnlineEXP.wsgi:application --bind 0.0.0.0:8000
    # ports:
    #   - 8000:8000
    # con esto exponemos el puerto a nginx, sustituyendo lo de arriba
    expose:
      - 8000
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web