# version: '3.7'
# build para local y expone puertos sin nginx
# services:
#   web:
#     build: ./
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - ./:/root/test_dock/
#     ports:
#       - 80:8000
#     # env_file:
#     #   - ./.env.dev
version: '3'

services:
  web:
    restart: always
    build: ./
    # ports:
    #   - "8000:8000"
    expose:
      - "8000"
    command: gunicorn OnlineEXP.wsgi:application -w 3  --bind 0.0.0.0:8000
    volumes:
      # - static:/var/www
      # - web-django:/usr/src/app
      - static:/root/test_dock/
      # - .:/root/test_dock/

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    expose:
      - "8000"
    # volumes:
    #   # cambiar!!!!!
    #   - static_volume:/root/test_dock/static/
    volumes:
      # - static:/var/www/
      - static:/root/test_dock/
    depends_on:
      - web

volumes:
  static: