# version: '3.7'

# services:
#   web:
#     build: ./
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - ./:/root/test_dock/
#     ports:
#       - 80:8000
#     # env_file:
#     #   - ./.env.dev


version: '3'

services:
  web:
    restart: always
    build: ./
    # ports:
    #   - "8000:8000"
    expose:
      - "8000"
    command: gunicorn OnlineEXP.wsgi:application -w 3  --bind 0.0.0.0:8000

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "8001:80"
    depends_on:
      - web