# Generated by Django 2.2.13 on 2020-06-22 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20200622_1826'),
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='license',
        ),
        migrations.AddField(
            model_name='code',
            name='is_event_code',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Event_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.Code')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
