# Generated by Django 2.2.13 on 2020-06-22 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20200622_1826'),
        ('user_account', '0002_auto_20200622_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='license',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_license', to='user_account.License'),
        ),
        migrations.AddField(
            model_name='profile',
            name='code_login',
            field=models.CharField(default='', max_length=149, unique=True),
        ),
        migrations.CreateModel(
            name='License_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.License')),
            ],
        ),
    ]
