# Generated by Django 2.2.13 on 2020-06-22 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0012_auto_20200622_1826'),
        ('user_account', '0003_auto_20200622_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='code_login',
        ),
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_code', to='user_account.Code'),
        ),
        migrations.AlterField(
            model_name='license_event',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event', unique=True),
        ),
        migrations.AlterField(
            model_name='license_event',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.License', unique=True),
        ),
        migrations.DeleteModel(
            name='User_Code',
        ),
    ]
