# Generated by Django 2.2.13 on 2020-06-24 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0005_remove_profile_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_user',
            name='event',
        ),
        migrations.RemoveField(
            model_name='event_user',
            name='user',
        ),
        migrations.RemoveField(
            model_name='license_event',
            name='event',
        ),
        migrations.RemoveField(
            model_name='license_event',
            name='license',
        ),
        migrations.DeleteModel(
            name='Event_Code',
        ),
        migrations.DeleteModel(
            name='Event_User',
        ),
        migrations.DeleteModel(
            name='License_event',
        ),
    ]
