"""
Django settings for OnlineEXP project.

Generated by 'django-admin startproject' using Django 2.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%pn0bm%roc=u7ms0+tqa0cfxl@cduy6&qh@8o#29#f+$h#%!lb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

NUM_SESSIONS_ALLOWED=1
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'events',
    "user_account",
    "colorfield",
    'django_countries',
    'ckeditor',
    "widget_tweaks",
    "import_export",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'user_account.middleware_one_session.OneSessionPerUserMiddleware',
]

ROOT_URLCONF = 'OnlineEXP.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'OnlineEXP.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db_order.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_L10N = True

USE_TZ = True

AUTHENTICATION_BACKENDS = [

    'user_account.auth_backend.PasswordlessAuthBackend',
    # 'user_account.utils.auth_backend.EmailAuthBackend',
    "django.contrib.auth.backends.ModelBackend",
    #login con OAUTH de redes sociales
    # "djoser.social.backends.facebook.FacebookOAuth2Override",
    # "social_core.backends.google.GoogleOAuth2",
    # "social_core.backends.steam.SteamOpenId",
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]


PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT = os.path.join(PROJECT_DIR, 'static')


MEDIA_URL = '/files/'
MEDIA_ROOT = os.path.join(BASE_DIR, "files")

CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"


# During development only
#
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' 


# on deploy 

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = "admin@glsteamedition.com"
EMAIL_PORT = 587
# # ejemplo de escribiendola en archivo en el server
# # EMAIL_HOST_PASSWORD =  "my_shitty_password" 
EMAIL_HOST_PASSWORD = "GLSTeamEdition2020?!"

IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg','pdf']

# TEST
# DESTINATARIOS_ORACION=["admin@glsteamedition.com","vintaw.01@gmail.com","alexis@thinkof.tech","rafaelgarcia.com@gmail.com"]
# DESTINATARIOS_TE=["admin@glsteamedition.com","vintaw.01@gmail.com","alexis@thinkof.tech","rafaelgarcia.com@gmail.com"]

#DEPLOY
DESTINATARIOS_ORACION=["maysosapavon@gmail.com ","ishaloly@gmail.com","amparo_pib@hotmail.com"]
DESTINATARIOS_TE=["lucyere.garcia@prodigy.net.mx"]


DEFAULT_FILE_STORAGE = 'OnlineEXP.storage.ASCIIFileSystemStorage'
# AUTH_PASSWORD_VALIDATORS = []